version: '3.4'

networks: 
  calculadora-dev:
    driver: bridge

services:
  calculadora:
    image: calculadora
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "20000:80"
    networks:
      - calculadora-dev